// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.1
// source: schema.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "motion_bridge";

export interface ClientHandshake {
  modelName: string;
}

export interface BodyLandmarks {
  landmarksData: number[];
}

export interface CaptureEventPacket {
  timestamp: number;
  actorId: number;
  handshake?: ClientHandshake | undefined;
  body?: BodyLandmarks | undefined;
}

export interface ProtoVector3 {
  x: number;
  y: number;
  z: number;
}

export interface ProtoQuaternion {
  x: number;
  y: number;
  z: number;
  w: number;
}

export interface BodyFrame {
  rootPosition: ProtoVector3 | undefined;
  boneRotations: ProtoQuaternion[];
}

export interface RigUpdatePacket {
  timestamp: number;
  actorId: number;
  body?: BodyFrame | undefined;
}

function createBaseClientHandshake(): ClientHandshake {
  return { modelName: "" };
}

export const ClientHandshake: MessageFns<ClientHandshake> = {
  encode(message: ClientHandshake, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelName !== "") {
      writer.uint32(10).string(message.modelName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientHandshake {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseClientHandshake();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.modelName = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ClientHandshake {
    return {
      modelName: isSet(object.modelName)
        ? globalThis.String(object.modelName)
        : isSet(object.model_name)
        ? globalThis.String(object.model_name)
        : "",
    };
  },

  toJSON(message: ClientHandshake): unknown {
    const obj: any = {};
    if (message.modelName !== "") {
      obj.modelName = message.modelName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientHandshake>, I>>(base?: I): ClientHandshake {
    return ClientHandshake.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientHandshake>, I>>(object: I): ClientHandshake {
    const message = createBaseClientHandshake();
    message.modelName = object.modelName ?? "";
    return message;
  },
};

function createBaseBodyLandmarks(): BodyLandmarks {
  return { landmarksData: [] };
}

export const BodyLandmarks: MessageFns<BodyLandmarks> = {
  encode(message: BodyLandmarks, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.landmarksData) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BodyLandmarks {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBodyLandmarks();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag === 13) {
              message.landmarksData.push(reader.float());

              continue;
            }

            if (tag === 10) {
              const end2 = reader.uint32() + reader.pos;
              while (reader.pos < end2) {
                message.landmarksData.push(reader.float());
              }

              continue;
            }

            break;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BodyLandmarks {
    return {
      landmarksData: globalThis.Array.isArray(object?.landmarksData)
        ? object.landmarksData.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.landmarks_data)
        ? object.landmarks_data.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: BodyLandmarks): unknown {
    const obj: any = {};
    if (message.landmarksData?.length) {
      obj.landmarksData = message.landmarksData;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BodyLandmarks>, I>>(base?: I): BodyLandmarks {
    return BodyLandmarks.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BodyLandmarks>, I>>(object: I): BodyLandmarks {
    const message = createBaseBodyLandmarks();
    message.landmarksData = object.landmarksData?.map((e) => e) || [];
    return message;
  },
};

function createBaseCaptureEventPacket(): CaptureEventPacket {
  return { timestamp: 0, actorId: 0, handshake: undefined, body: undefined };
}

export const CaptureEventPacket: MessageFns<CaptureEventPacket> = {
  encode(message: CaptureEventPacket, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).uint64(message.timestamp);
    }
    if (message.actorId !== 0) {
      writer.uint32(16).uint32(message.actorId);
    }
    if (message.handshake !== undefined) {
      ClientHandshake.encode(message.handshake, writer.uint32(26).fork()).join();
    }
    if (message.body !== undefined) {
      BodyLandmarks.encode(message.body, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CaptureEventPacket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCaptureEventPacket();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.timestamp = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.actorId = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.handshake = ClientHandshake.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.body = BodyLandmarks.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CaptureEventPacket {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      actorId: isSet(object.actorId)
        ? globalThis.Number(object.actorId)
        : isSet(object.actor_id)
        ? globalThis.Number(object.actor_id)
        : 0,
      handshake: isSet(object.handshake) ? ClientHandshake.fromJSON(object.handshake) : undefined,
      body: isSet(object.body) ? BodyLandmarks.fromJSON(object.body) : undefined,
    };
  },

  toJSON(message: CaptureEventPacket): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.actorId !== 0) {
      obj.actorId = Math.round(message.actorId);
    }
    if (message.handshake !== undefined) {
      obj.handshake = ClientHandshake.toJSON(message.handshake);
    }
    if (message.body !== undefined) {
      obj.body = BodyLandmarks.toJSON(message.body);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CaptureEventPacket>, I>>(base?: I): CaptureEventPacket {
    return CaptureEventPacket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CaptureEventPacket>, I>>(object: I): CaptureEventPacket {
    const message = createBaseCaptureEventPacket();
    message.timestamp = object.timestamp ?? 0;
    message.actorId = object.actorId ?? 0;
    message.handshake = (object.handshake !== undefined && object.handshake !== null)
      ? ClientHandshake.fromPartial(object.handshake)
      : undefined;
    message.body = (object.body !== undefined && object.body !== null)
      ? BodyLandmarks.fromPartial(object.body)
      : undefined;
    return message;
  },
};

function createBaseProtoVector3(): ProtoVector3 {
  return { x: 0, y: 0, z: 0 };
}

export const ProtoVector3: MessageFns<ProtoVector3> = {
  encode(message: ProtoVector3, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(13).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(21).float(message.y);
    }
    if (message.z !== 0) {
      writer.uint32(29).float(message.z);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoVector3 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtoVector3();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 13) {
              break;
            }

            message.x = reader.float();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.y = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.z = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtoVector3 {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
    };
  },

  toJSON(message: ProtoVector3): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.z !== 0) {
      obj.z = message.z;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoVector3>, I>>(base?: I): ProtoVector3 {
    return ProtoVector3.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoVector3>, I>>(object: I): ProtoVector3 {
    const message = createBaseProtoVector3();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.z = object.z ?? 0;
    return message;
  },
};

function createBaseProtoQuaternion(): ProtoQuaternion {
  return { x: 0, y: 0, z: 0, w: 0 };
}

export const ProtoQuaternion: MessageFns<ProtoQuaternion> = {
  encode(message: ProtoQuaternion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(13).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(21).float(message.y);
    }
    if (message.z !== 0) {
      writer.uint32(29).float(message.z);
    }
    if (message.w !== 0) {
      writer.uint32(37).float(message.w);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoQuaternion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtoQuaternion();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 13) {
              break;
            }

            message.x = reader.float();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.y = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.z = reader.float();
            continue;
          }
          case 4: {
            if (tag !== 37) {
              break;
            }

            message.w = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtoQuaternion {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
      w: isSet(object.w) ? globalThis.Number(object.w) : 0,
    };
  },

  toJSON(message: ProtoQuaternion): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.z !== 0) {
      obj.z = message.z;
    }
    if (message.w !== 0) {
      obj.w = message.w;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoQuaternion>, I>>(base?: I): ProtoQuaternion {
    return ProtoQuaternion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoQuaternion>, I>>(object: I): ProtoQuaternion {
    const message = createBaseProtoQuaternion();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.z = object.z ?? 0;
    message.w = object.w ?? 0;
    return message;
  },
};

function createBaseBodyFrame(): BodyFrame {
  return { rootPosition: undefined, boneRotations: [] };
}

export const BodyFrame: MessageFns<BodyFrame> = {
  encode(message: BodyFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rootPosition !== undefined) {
      ProtoVector3.encode(message.rootPosition, writer.uint32(10).fork()).join();
    }
    for (const v of message.boneRotations) {
      ProtoQuaternion.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BodyFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBodyFrame();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.rootPosition = ProtoVector3.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.boneRotations.push(ProtoQuaternion.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BodyFrame {
    return {
      rootPosition: isSet(object.rootPosition)
        ? ProtoVector3.fromJSON(object.rootPosition)
        : isSet(object.root_position)
        ? ProtoVector3.fromJSON(object.root_position)
        : undefined,
      boneRotations: globalThis.Array.isArray(object?.boneRotations)
        ? object.boneRotations.map((e: any) => ProtoQuaternion.fromJSON(e))
        : globalThis.Array.isArray(object?.bone_rotations)
        ? object.bone_rotations.map((e: any) => ProtoQuaternion.fromJSON(e))
        : [],
    };
  },

  toJSON(message: BodyFrame): unknown {
    const obj: any = {};
    if (message.rootPosition !== undefined) {
      obj.rootPosition = ProtoVector3.toJSON(message.rootPosition);
    }
    if (message.boneRotations?.length) {
      obj.boneRotations = message.boneRotations.map((e) => ProtoQuaternion.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BodyFrame>, I>>(base?: I): BodyFrame {
    return BodyFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BodyFrame>, I>>(object: I): BodyFrame {
    const message = createBaseBodyFrame();
    message.rootPosition = (object.rootPosition !== undefined && object.rootPosition !== null)
      ? ProtoVector3.fromPartial(object.rootPosition)
      : undefined;
    message.boneRotations = object.boneRotations?.map((e) => ProtoQuaternion.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRigUpdatePacket(): RigUpdatePacket {
  return { timestamp: 0, actorId: 0, body: undefined };
}

export const RigUpdatePacket: MessageFns<RigUpdatePacket> = {
  encode(message: RigUpdatePacket, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).uint64(message.timestamp);
    }
    if (message.actorId !== 0) {
      writer.uint32(16).uint32(message.actorId);
    }
    if (message.body !== undefined) {
      BodyFrame.encode(message.body, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RigUpdatePacket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRigUpdatePacket();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.timestamp = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.actorId = reader.uint32();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.body = BodyFrame.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RigUpdatePacket {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      actorId: isSet(object.actorId)
        ? globalThis.Number(object.actorId)
        : isSet(object.actor_id)
        ? globalThis.Number(object.actor_id)
        : 0,
      body: isSet(object.body) ? BodyFrame.fromJSON(object.body) : undefined,
    };
  },

  toJSON(message: RigUpdatePacket): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.actorId !== 0) {
      obj.actorId = Math.round(message.actorId);
    }
    if (message.body !== undefined) {
      obj.body = BodyFrame.toJSON(message.body);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RigUpdatePacket>, I>>(base?: I): RigUpdatePacket {
    return RigUpdatePacket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RigUpdatePacket>, I>>(object: I): RigUpdatePacket {
    const message = createBaseRigUpdatePacket();
    message.timestamp = object.timestamp ?? 0;
    message.actorId = object.actorId ?? 0;
    message.body = (object.body !== undefined && object.body !== null) ? BodyFrame.fromPartial(object.body) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
