// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.1
// source: schema.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "mocap";

export interface Point3D {
  id: number;
  x: number;
  y: number;
  z: number;
  visibility: number;
}

export interface Handshake {
  skeletonType: string;
}

export interface MocapFrame {
  timestamp: number;
  landmarks: Point3D[];
}

export interface ClientMessage {
  handshake?: Handshake | undefined;
  frame?: MocapFrame | undefined;
}

export interface BoneRotation {
  boneId: number;
  qx: number;
  qy: number;
  qz: number;
  qw: number;
}

export interface SolverFrame {
  rootX: number;
  rootY: number;
  rootZ: number;
  bones: BoneRotation[];
  timestamp: number;
}

function createBasePoint3D(): Point3D {
  return { id: 0, x: 0, y: 0, z: 0, visibility: 0 };
}

export const Point3D: MessageFns<Point3D> = {
  encode(message: Point3D, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.x !== 0) {
      writer.uint32(21).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(29).float(message.y);
    }
    if (message.z !== 0) {
      writer.uint32(37).float(message.z);
    }
    if (message.visibility !== 0) {
      writer.uint32(45).float(message.visibility);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Point3D {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePoint3D();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.x = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.y = reader.float();
            continue;
          }
          case 4: {
            if (tag !== 37) {
              break;
            }

            message.z = reader.float();
            continue;
          }
          case 5: {
            if (tag !== 45) {
              break;
            }

            message.visibility = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Point3D {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
      visibility: isSet(object.visibility) ? globalThis.Number(object.visibility) : 0,
    };
  },

  toJSON(message: Point3D): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.z !== 0) {
      obj.z = message.z;
    }
    if (message.visibility !== 0) {
      obj.visibility = message.visibility;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Point3D>, I>>(base?: I): Point3D {
    return Point3D.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Point3D>, I>>(object: I): Point3D {
    const message = createBasePoint3D();
    message.id = object.id ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.z = object.z ?? 0;
    message.visibility = object.visibility ?? 0;
    return message;
  },
};

function createBaseHandshake(): Handshake {
  return { skeletonType: "" };
}

export const Handshake: MessageFns<Handshake> = {
  encode(message: Handshake, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.skeletonType !== "") {
      writer.uint32(10).string(message.skeletonType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Handshake {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseHandshake();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.skeletonType = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Handshake {
    return {
      skeletonType: isSet(object.skeletonType)
        ? globalThis.String(object.skeletonType)
        : isSet(object.skeleton_type)
        ? globalThis.String(object.skeleton_type)
        : "",
    };
  },

  toJSON(message: Handshake): unknown {
    const obj: any = {};
    if (message.skeletonType !== "") {
      obj.skeletonType = message.skeletonType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Handshake>, I>>(base?: I): Handshake {
    return Handshake.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Handshake>, I>>(object: I): Handshake {
    const message = createBaseHandshake();
    message.skeletonType = object.skeletonType ?? "";
    return message;
  },
};

function createBaseMocapFrame(): MocapFrame {
  return { timestamp: 0, landmarks: [] };
}

export const MocapFrame: MessageFns<MocapFrame> = {
  encode(message: MocapFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).uint64(message.timestamp);
    }
    for (const v of message.landmarks) {
      Point3D.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MocapFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMocapFrame();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.timestamp = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.landmarks.push(Point3D.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MocapFrame {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      landmarks: globalThis.Array.isArray(object?.landmarks)
        ? object.landmarks.map((e: any) => Point3D.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MocapFrame): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.landmarks?.length) {
      obj.landmarks = message.landmarks.map((e) => Point3D.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MocapFrame>, I>>(base?: I): MocapFrame {
    return MocapFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MocapFrame>, I>>(object: I): MocapFrame {
    const message = createBaseMocapFrame();
    message.timestamp = object.timestamp ?? 0;
    message.landmarks = object.landmarks?.map((e) => Point3D.fromPartial(e)) || [];
    return message;
  },
};

function createBaseClientMessage(): ClientMessage {
  return { handshake: undefined, frame: undefined };
}

export const ClientMessage: MessageFns<ClientMessage> = {
  encode(message: ClientMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.handshake !== undefined) {
      Handshake.encode(message.handshake, writer.uint32(10).fork()).join();
    }
    if (message.frame !== undefined) {
      MocapFrame.encode(message.frame, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseClientMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.handshake = Handshake.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.frame = MocapFrame.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ClientMessage {
    return {
      handshake: isSet(object.handshake) ? Handshake.fromJSON(object.handshake) : undefined,
      frame: isSet(object.frame) ? MocapFrame.fromJSON(object.frame) : undefined,
    };
  },

  toJSON(message: ClientMessage): unknown {
    const obj: any = {};
    if (message.handshake !== undefined) {
      obj.handshake = Handshake.toJSON(message.handshake);
    }
    if (message.frame !== undefined) {
      obj.frame = MocapFrame.toJSON(message.frame);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientMessage>, I>>(base?: I): ClientMessage {
    return ClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientMessage>, I>>(object: I): ClientMessage {
    const message = createBaseClientMessage();
    message.handshake = (object.handshake !== undefined && object.handshake !== null)
      ? Handshake.fromPartial(object.handshake)
      : undefined;
    message.frame = (object.frame !== undefined && object.frame !== null)
      ? MocapFrame.fromPartial(object.frame)
      : undefined;
    return message;
  },
};

function createBaseBoneRotation(): BoneRotation {
  return { boneId: 0, qx: 0, qy: 0, qz: 0, qw: 0 };
}

export const BoneRotation: MessageFns<BoneRotation> = {
  encode(message: BoneRotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.boneId !== 0) {
      writer.uint32(8).uint32(message.boneId);
    }
    if (message.qx !== 0) {
      writer.uint32(21).float(message.qx);
    }
    if (message.qy !== 0) {
      writer.uint32(29).float(message.qy);
    }
    if (message.qz !== 0) {
      writer.uint32(37).float(message.qz);
    }
    if (message.qw !== 0) {
      writer.uint32(45).float(message.qw);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BoneRotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBoneRotation();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.boneId = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.qx = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.qy = reader.float();
            continue;
          }
          case 4: {
            if (tag !== 37) {
              break;
            }

            message.qz = reader.float();
            continue;
          }
          case 5: {
            if (tag !== 45) {
              break;
            }

            message.qw = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BoneRotation {
    return {
      boneId: isSet(object.boneId)
        ? globalThis.Number(object.boneId)
        : isSet(object.bone_id)
        ? globalThis.Number(object.bone_id)
        : 0,
      qx: isSet(object.qx) ? globalThis.Number(object.qx) : 0,
      qy: isSet(object.qy) ? globalThis.Number(object.qy) : 0,
      qz: isSet(object.qz) ? globalThis.Number(object.qz) : 0,
      qw: isSet(object.qw) ? globalThis.Number(object.qw) : 0,
    };
  },

  toJSON(message: BoneRotation): unknown {
    const obj: any = {};
    if (message.boneId !== 0) {
      obj.boneId = Math.round(message.boneId);
    }
    if (message.qx !== 0) {
      obj.qx = message.qx;
    }
    if (message.qy !== 0) {
      obj.qy = message.qy;
    }
    if (message.qz !== 0) {
      obj.qz = message.qz;
    }
    if (message.qw !== 0) {
      obj.qw = message.qw;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BoneRotation>, I>>(base?: I): BoneRotation {
    return BoneRotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BoneRotation>, I>>(object: I): BoneRotation {
    const message = createBaseBoneRotation();
    message.boneId = object.boneId ?? 0;
    message.qx = object.qx ?? 0;
    message.qy = object.qy ?? 0;
    message.qz = object.qz ?? 0;
    message.qw = object.qw ?? 0;
    return message;
  },
};

function createBaseSolverFrame(): SolverFrame {
  return { rootX: 0, rootY: 0, rootZ: 0, bones: [], timestamp: 0 };
}

export const SolverFrame: MessageFns<SolverFrame> = {
  encode(message: SolverFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rootX !== 0) {
      writer.uint32(13).float(message.rootX);
    }
    if (message.rootY !== 0) {
      writer.uint32(21).float(message.rootY);
    }
    if (message.rootZ !== 0) {
      writer.uint32(29).float(message.rootZ);
    }
    for (const v of message.bones) {
      BoneRotation.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).uint64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SolverFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSolverFrame();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 13) {
              break;
            }

            message.rootX = reader.float();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.rootY = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 29) {
              break;
            }

            message.rootZ = reader.float();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.bones.push(BoneRotation.decode(reader, reader.uint32()));
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.timestamp = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SolverFrame {
    return {
      rootX: isSet(object.rootX)
        ? globalThis.Number(object.rootX)
        : isSet(object.root_x)
        ? globalThis.Number(object.root_x)
        : 0,
      rootY: isSet(object.rootY)
        ? globalThis.Number(object.rootY)
        : isSet(object.root_y)
        ? globalThis.Number(object.root_y)
        : 0,
      rootZ: isSet(object.rootZ)
        ? globalThis.Number(object.rootZ)
        : isSet(object.root_z)
        ? globalThis.Number(object.root_z)
        : 0,
      bones: globalThis.Array.isArray(object?.bones) ? object.bones.map((e: any) => BoneRotation.fromJSON(e)) : [],
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: SolverFrame): unknown {
    const obj: any = {};
    if (message.rootX !== 0) {
      obj.rootX = message.rootX;
    }
    if (message.rootY !== 0) {
      obj.rootY = message.rootY;
    }
    if (message.rootZ !== 0) {
      obj.rootZ = message.rootZ;
    }
    if (message.bones?.length) {
      obj.bones = message.bones.map((e) => BoneRotation.toJSON(e));
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SolverFrame>, I>>(base?: I): SolverFrame {
    return SolverFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SolverFrame>, I>>(object: I): SolverFrame {
    const message = createBaseSolverFrame();
    message.rootX = object.rootX ?? 0;
    message.rootY = object.rootY ?? 0;
    message.rootZ = object.rootZ ?? 0;
    message.bones = object.bones?.map((e) => BoneRotation.fromPartial(e)) || [];
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
